### ISSUE TITLE
Cannot run tests

### ISSUE THREAD

**Issue by jakoblind** [bcoin-org/plasma#2]
```
> npm run test

> bcoin-plasma@0.0.1 test /Users/jakoblind/dev/plasma
> mocha --reporter spec test/*-test.js

module.js:327
    throw err;
    ^

Error: Cannot find module '../elkrem'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/jakoblind/dev/plasma/test/channel-test.js:12:14)
    at Module._compile (module.js:397:26)
    at Object.Module._extensions..js (module.js:404:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at /Users/jakoblind/dev/plasma/node_modules/mocha/lib/mocha.js:220:27
    at Array.forEach (native)
    at Mocha.loadFiles (/Users/jakoblind/dev/plasma/node_modules/mocha/lib/mocha.js:217:14)
    at Mocha.run (/Users/jakoblind/dev/plasma/node_modules/mocha/lib/mocha.js:485:10)
    at Object.<anonymous> (/Users/jakoblind/dev/plasma/node_modules/mocha/bin/_mocha:403:18)
    at Module._compile (module.js:397:26)
    at Object.Module._extensions..js (module.js:404:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:429:10)
    at startup (node.js:139:18)
    at node.js:999:3
```

What is module `elkrem` and where can I get it?

**Comment by chjj** [comment]
Hmm, blame a refactor for that. Fixing.
